export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import styles from "./scss/globals.module.scss";

const {appStyled} = styles
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={appStyled}>{children}</body>
    </html>
  )
}
